steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/python-web-app-images/python-web-app:$COMMIT_SHA', '.']

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/python-web-app-images/python-web-app:$COMMIT_SHA']

- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
    - 'deploy'
    - 'releases'
    - 'create'
    - 'release-$SHORT_SHA'
    - '--delivery-pipeline=python-app-pipeline'
    - '--region=us-central1'
    - '--images=python-web-app-image=us-central1-docker.pkg.dev/$PROJECT_ID/python-web-app-images/python-web-app:$COMMIT_SHA'
    